
name_of_project: 'Laplace'
num_cores: 5 # How many cores would you like to use for travel time calculations? (it will increase memory cost)

extend_grids: True
degree_padding: 0.1 # This region is appended to the lat_range and lon_range values above, and is used as a `padding' region, where we compute travel times, and simulate events in this region, yet train to predict zero for all labels in this area. This way, sources just outside the domain of interest arn't falsely mis-located inside the region (since the model learns what `exterior' events look like, to some extent).
number_of_grids: 5 # Number of distinct spatial graphs to create (this reduced slight bias that can result from only using one spatial graph)
number_of_spatial_nodes: 1000 # Number of nodes per spatial graph
n_features: 45
n_cayley: 11

## TRAIN
n_samples: 2000
scale_val: 50000
norm_version: 2
max_val: 0.1
min_val: -3.5
n_ver_save: 1
device: 'cuda' # or 'cpu'

## Graph params
k_spc_edges: 15

## Training params
n_batch: 100
n_epochs: 150000 # add 1, so it saves on last iteration (since it saves every 100 steps)
use_only_complex: True
path_to_data: '/scratch/users/taiyi/ForIan/complex_08162023/'
